server:
  port: 8081
  
# database configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: krishna24
    driver-class-name: com.mysql.cj.jdbc.Driver
    
# hibernate configurations.   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    